# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.9 on 2024-09-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("global", "Global"), ("channel", "Channel")], default="global", max_length=256
                    ),
                ),
                ("channel_idx", models.CharField(blank=True, max_length=128, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("secret_key", models.CharField(max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
